### ISSUE TITLE
gi.require_version("Secret", "1") - ValueError: Namespace Secret not available

### ISSUE THREAD

**Issue by gnloch** [conda-forge/libsecret-feedstock#6]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I am not sure if this is the correct place to raise this issue. Apologies it it isn´t.

I am trying to use a python code on a conda environment which is breaking with the following code:
```python
import gi
gi.require_version("Secret", "1")
```
This site (https://lazka.github.io/pgi-docs/#Secret-1) informs that libsecret provides `Secret`.
I was able to use this code snippet on ubuntu by installing the package `gir1.2-secret-1` and using ubuntu's python interpreter.
Trying to do the same on conda, I installed the `libsecret` package from conda-forge, but it did not work:
```
(aiq) [gloch@windhelm aiq_remote]$ python
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version("Secret", "1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gloch/.miniconda3/envs/aiq/lib/python3.7/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
```
So, I would like to know if there is any other conda package that I should install to make this code snippet work? 

<br/>
Environment (<code>conda list</code>):
<details>

```
(aiq) [gloch@windhelm aiq_remote]$ conda list
# packages in environment at /home/gloch/.miniconda3/envs/aiq:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
adal                      1.2.7                    pypi_0    pypi
azure-common              1.1.27                   pypi_0    pypi
azure-core                1.18.0                   pypi_0    pypi
azure-graphrbac           0.61.1                   pypi_0    pypi
azure-identity            1.6.1                    pypi_0    pypi
azure-keyvault-secrets    4.3.0                    pypi_0    pypi
azure-mgmt-authorization  0.61.0                   pypi_0    pypi
azure-mgmt-containerregistry 8.1.0                    pypi_0    pypi
azure-mgmt-core           1.3.0                    pypi_0    pypi
azure-mgmt-keyvault       9.1.0                    pypi_0    pypi
azure-mgmt-resource       13.0.0                   pypi_0    pypi
azure-mgmt-storage        11.2.0                   pypi_0    pypi
azureml-core              1.34.0                   pypi_0    pypi
backports-tempfile        1.0                      pypi_0    pypi
backports-weakref         1.0.post1                pypi_0    pypi
ca-certificates           2021.7.5             h06a4308_1  
cairo                     1.16.0               hf32fb01_1  
certifi                   2021.5.30        py37h06a4308_0  
cffi                      1.14.6                   pypi_0    pypi
charset-normalizer        2.0.5                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
cryptography              3.4.8                    pypi_0    pypi
docker                    5.0.2                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
gettext                   0.21.0               hf68c758_0  
glib                      2.68.2               h36276a3_0  
gobject-introspection     1.68.0           py37h2109141_1  
icu                       58.2                 he6710b0_3  
idna                      3.2                      pypi_0    pypi
importlib-metadata        4.8.1                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
jeepney                   0.7.1                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
jsonpickle                2.0.0                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgcrypt                 1.9.3                h27cfd23_0  
libglib                   2.68.2               h3e27bee_0    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libgpg-error              1.42                 h2531618_0  
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libsecret                 0.18.8               h3560a44_1    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
msal                      1.14.0                   pypi_0    pypi
msal-extensions           0.3.0                    pypi_0    pypi
msrest                    0.6.21                   pypi_0    pypi
msrestazure               0.6.4                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
ndg-httpsclient           0.5.1                    pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
pathspec                  0.9.0                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pip                       21.2.2           py37h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
portalocker               1.7.1                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pycairo                   1.19.1           py37h708ec4a_0  
pycparser                 2.20                     pypi_0    pypi
pygobject                 3.40.1           py37he6fa580_1    conda-forge
pyjwt                     2.1.0                    pypi_0    pypi
pyopenssl                 20.0.1                   pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.1                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
ruamel-yaml               0.17.4                   pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
secretstorage             3.3.1                    pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.10               hbc83047_0  
typing-extensions         3.10.0.2                 pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
websocket-client          1.2.1                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zipp                      3.5.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(aiq) [gloch@windhelm aiq_remote]$ conda info

     active environment : aiq
    active env location : /home/gloch/.miniconda3/envs/aiq
            shell level : 1
       user config file : /home/gloch/.condarc
 populated config files : /home/gloch/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.14.3=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/gloch/.miniconda3  (writable)
      conda av data dir : /home/gloch/.miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gloch/.miniconda3/pkgs
                          /home/gloch/.conda/pkgs
       envs directories : /home/gloch/.miniconda3/envs
                          /home/gloch/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.10 Linux/5.14.3-arch1-1 arch/ glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by adimenia** [comment]
Having the same issue, looking for a solution

**Comment by ianhelle** [comment]
Hah - I just came to open the same issue.

I've tracked the problem down to a missing typelib. I'm not 100% about the inner workings of Conda but it seems that it has its own version (per environment) of /usr/lib/girepository-1.0. This is where the .typelib binaries that gi needs to enumerate the interfaces to things like libsecret.
When using the system python it correctly finds Secret-1.typelib in /usr/lib/girepository.
When using Conda it is looking for typelibs in /anaconda3/lib/girepository-1.0/ (for the base env - each env has a corresponding folder in anaconda3/envs/env_name/lib).

A workaround for this is to copy the Secret-1.typelib to the lib/girepository-1.0 for the env where you are using libsecret. Although this is not a very pleasant thing to have to do every time.

So this recipe (I think) should be installing a version in the base (or env) lib/girepository-1.0. 

If I knew anything about how Conda recipes work I'd submit a PR but I can't figure out where to configure this.

**Comment by nehaljwani** [comment]
Thank you for pointing in the right direction, @ianhelle ! I've updated the recipe to include the missing typelib.

```
❯❯❯ conda list libsecret
# packages in environment at /tmp/nwani_1654862177/dev:
#
# Name                    Version                   Build  Channel
libsecret                 0.18.8               h329b89f_2    conda-forge

❯❯❯ python -c 'import gi; gi.require_version("Secret", "1")'
❯❯❯ echo $?
0

❯❯❯ ls $CONDA_PREFIX/lib/girepository-1.0/Secret-1.typelib
/tmp/nwani_1654862177/dev/lib/girepository-1.0/Secret-1.typelib
```

**Comment by ianhelle** [comment]
@nehaljwani - thanks so much for getting on this so quickly. Haven't yet tested it but looks like it should do the job!
Awesome stuff!
